add_newline = true
format = "$directory$git_branch$git_status$python$nodejs$rust$golang$cmd_duration$line_break$character"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 4
truncate_to_repo = false
style = "bold cyan"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
style = "bold purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "yellow"

[cmd_duration]
min_time = 1000
format = "[$duration]($style) "
style = "dimmed yellow"

[python]
format = "[py $version]($style) "

[nodejs]
format = "[node $version]($style) "

[rust]
format = "[rs $version]($style) "

[golang]
format = "[go $version]($style) "
