[Metadata]
Name=Omarchy Dark
Version=1
Author=allen
Description=Dark theme aligned with Omarchy palette
ScaleWithDPI=True

[InputPanel]
NormalColor=#d7dce5
HighlightCandidateColor=#e3e7ee
HighlightColor=#e3e7ee
HighlightBackgroundColor=#3a3a3a
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=8
Right=8
Top=6
Bottom=6

[InputPanel/ContentMargin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/Background]
Color=#1c1c1c66
BorderColor=#44444466
BorderWidth=1

[InputPanel/Background/Margin]
Left=3
Right=3
Top=3
Bottom=3

[InputPanel/Highlight]
Color=#3a3a3a

[InputPanel/Highlight/Margin]
Left=6
Right=6
Top=4
Bottom=4

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=6
Right=6
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=6
Right=6
Top=4
Bottom=4

[Menu]
NormalColor=#d7dce5
HighlightCandidateColor=#e3e7ee

[Menu/Background]
Color=#1c1c1c66
BorderColor=#44444466
BorderWidth=1

[Menu/Background/Margin]
Left=3
Right=3
Top=3
Bottom=3

[Menu/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/Highlight]
Color=#3a3a3a

[Menu/Highlight/Margin]
Left=6
Right=6
Top=4
Bottom=4

[Menu/Separator]
Color=#555555

[Menu/TextMargin]
Left=6
Right=6
Top=5
Bottom=5
